export const vertexShader = [
  'uniform float uMix,uTime,uPixel,uSize,uBurst; uniform vec2 uMouse; uniform float uAspect;',
  'attribute vec3 aTo; attribute float aRand; attribute float aSize;',
  'varying float vR; varying float vDepth; varying float vPush;',
  'void main(){',
  ' float t=clamp(uMix*1.7-aRand*.7,0.,1.); t=t*t*(3.-2.*t);',
  ' vec3 p=mix(position,aTo,t);',
  ' float sw=sin(t*3.14159);',
  ' p+=vec3(sin(aRand*40.+uTime*.8),cos(aRand*33.+uTime*.7),sin(aRand*57.+uTime*.9))*sw*.6;',
  ' vec3 dir=normalize(p+vec3(.0001));',
  ' p+=dir*sin(uTime*.9+aRand*6.28)*.02;',
  ' p+=dir*uBurst*(.4+aRand*1.8);',
  ' vec4 mv=modelViewMatrix*vec4(p,1.);',
  ' vec4 clip=projectionMatrix*mv;',
  ' vec2 ndc=clip.xy/clip.w; vec2 d=ndc-uMouse; d.x*=uAspect;',
  ' float push=smoothstep(.45,0.,length(d));',
  ' vec2 off=normalize(d+vec2(.0001))*push*.17; off.x/=uAspect;',
  ' clip.xy+=off*clip.w;',
  ' gl_Position=clip;',
  ' gl_PointSize=aSize*uPixel*(uSize/-mv.z)*(1.+push*.8);',
  ' vR=aRand; vDepth=clamp((-mv.z-3.2)/3.,0.,1.); vPush=push;',
  '}',
].join('\n');

export const fragmentShader = [
  'precision mediump float; uniform vec3 uA,uB; uniform float uAlpha;',
  'varying float vR; varying float vDepth; varying float vPush;',
  'void main(){',
  ' vec2 c=gl_PointCoord-.5; float d=length(c); if(d>.5) discard;',
  ' float a=pow(smoothstep(.5,0.,d),1.5);',
  ' vec3 col=mix(uA,uB,clamp(vR*.7+vPush*1.3,0.,1.)); col=mix(col,vec3(1.),vPush*.5);',
  ' gl_FragColor=vec4(col,a*uAlpha*mix(1.,.35,vDepth));',
  '}',
].join('\n');
